# nonk8s
# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: typecho
spec:
  enabled: true
  requires: ">=2.11.0"
  author:
    name: mashirot
    website: https://github.com/ShiinaKin
  logo: logo.png
  configMapName: plugin-typecho-configmap
  settingName: plugin-typecho-settings
  homepage: https://github.com/ShiinaKin/halo-plugin-typecho#readme
  repo: https://github.com/ShiinaKin/halo-plugin-typecho
  issues: https://github.com/ShiinaKin/halo-plugin-typecho/issues
  displayName: "Typecho文章导入"
  description: "按文章分类导入"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/ShiinaKin/halo-plugin-typecho/blob/main/LICENSE"
