name: CI
on:
    push:
        branches:
            - main
            - dev
        tags:
            - "v*"
    pull_request:
        branches:
            - main
            - dev
            -
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            -   name: Setup Environment
                uses: halo-sigs/actions/plugin-setup-env@v1
                with:
                    cache-dept-path: ui/pnpm-lock.yaml
                    skip-node-setup: false
                    node-version: 20
                    pnpm-version: 9
                    java-version: 17

            -   name: Install UI Packages
                run: cd ui && pnpm install

            -   name: Build
                run: ./gradlew clean build

            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: halo-plugin-typecho-artifact
                    path: build/libs
                    retention-days: 1

    release:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: hoshizora-pics-artifact
                  path: build

            - name: Generate Changelog
              run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt

            - name: release
              uses: softprops/action-gh-release@v2
              with:
                  body_path: ${{ github.workspace }}-CHANGELOG.txt
                  files: build/*
